# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsonrestore',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
