# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 18:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_jsonrestore_timestamp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JsonRestore',
        ),
    ]
